import { Service, Category } from "./types";

export const servicesData: Service[] = [
  {
    id: 1,
    title: "KESSRA Training 1",
    instructor: "Andre Muniz",
    category: "coaching",
    price: 50,
    rating: 4.8,
    students: 245,
    duration: "8 weeks",
    image: "/assets/card-placeholder.png",
    description:
      "Complete training program with expert instructors to support your development.",
    tags: ["Professional", "Certification"],
    datePosted: "2025-07-01",
  },
  {
    id: 2,
    title: "UI/UX MasterClass 2",
    instructor: "Andre Muniz",
    category: "design",
    price: 155,
    rating: 4.9,
    students: 189,
    duration: "6 weeks",
    image: "/assets/card-placeholder.png",
    description:
      "Master UI/UX design principles with hands-on projects and expert guidance.",
    tags: ["Design", "UI/UX"],
    datePosted: "2025-07-02",
  },
  {
    id: 3,
    title: "Career Strategy Session 3",
    instructor: "Andre Muniz",
    category: "coaching",
    price: 75,
    rating: 4.7,
    students: 156,
    duration: "2 hours",
    image: "/assets/card-placeholder.png",
    description:
      "Strategic planning session to advance your career with expert advice.",
    tags: ["Career", "Strategy"],
    datePosted: "2025-06-30",
  },
  {
    id: 4,
    title: "UX Conference 4",
    instructor: "Andre Muniz",
    category: "conference",
    price: 300,
    rating: 4.8,
    students: 324,
    duration: "3 days",
    image: "/assets/card-placeholder.png",
    description:
      "Premium UX conference with industry experts and networking opportunities.",
    tags: ["Conference", "UX"],
    datePosted: "2025-07-05",
    type: "event",
  },
  {
    id: 5,
    title: "Food Festival 5",
    instructor: "Andre Muniz",
    category: "event",
    price: 25,
    rating: 4.6,
    students: 289,
    duration: "1 day",
    image: "/assets/card-placeholder.png",
    description: "Culinary experience with expert chefs and food enthusiasts.",
    tags: ["Food", "Festival"],
    datePosted: "2025-07-03",
    type: "event",
  },
  {
    id: 6,
    title: "Web Development 6",
    instructor: "Andre Muniz",
    category: "courses",
    price: 450,
    rating: 4.9,
    students: 412,
    duration: "12 weeks",
    image: "/assets/card-placeholder.png",
    description: "Complete web development bootcamp with modern technologies.",
    tags: ["Programming", "Web"],
    datePosted: "2025-07-04",
  },
  {
    id: 7,
    title: "Career Coaching 7",
    instructor: "Andre Muniz",
    category: "coaching",
    price: 120,
    rating: 4.8,
    students: 178,
    duration: "4 weeks",
    image: "/assets/card-placeholder.png",
    description:
      "Personal career coaching to help you achieve your professional goals.",
    tags: ["Career", "Coaching"],
    datePosted: "2025-07-06",
  },
  {
    id: 8,
    title: "Content Writing 8",
    instructor: "Andre Muniz",
    category: "writing",
    price: 85,
    rating: 4.7,
    students: 234,
    duration: "6 weeks",
    image: "/assets/card-placeholder.png",
    description: "Master content writing techniques with practical exercises.",
    tags: ["Writing", "Content"],
    datePosted: "2025-07-01",
  },
  {
    id: 9,
    title: "Business Consultation 9",
    instructor: "Andre Muniz",
    category: "consultation",
    price: 200,
    rating: 4.5,
    students: 98,
    duration: "1 hour",
    image: "/assets/card-placeholder.png",
    description: "Professional business consultation to grow your enterprise.",
    tags: ["Business", "Consultation"],
    datePosted: "2025-07-07",
  },
  {
    id: 10,
    title: "Product Development Workshop 10",
    instructor: "Andre Muniz",
    category: "products",
    price: 350,
    rating: 4.7,
    students: 156,
    duration: "2 weeks",
    image: "/assets/card-placeholder.png",
    description: "Learn product development from ideation to launch.",
    tags: ["Product", "Development"],
    datePosted: "2025-07-08",
  },
];

export const serviceProvidersData = [
  {
    id: 1,
    name: "Alice Mwende",
    title: "Certified UI/UX Designer",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description:
      "Helping people gain clarity and confidence in life transitions.",
    tags: ["Product Designer", "User Experience"],
    category: "design",
  },
  {
    id: 2,
    name: "Daniel Otieno",
    title: "Digital Marketing Strategist",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping small businesses grow online without any experience.",
    tags: ["Coaching", "Personal Growth"],
    category: "consultation",
  },
  {
    id: 3,
    name: "Fatima Yousuf",
    title: "Career Development Coach",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description:
      "Guiding young professionals in building resumes and interview skills.",
    tags: ["Coaching", "Personal Growth"],
    category: "coaching",
  },
  {
    id: 4,
    name: "George Njoroge",
    title: "Fitness & Nutrition Coach",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description:
      "I create custom workout and diet plans for busy professionals.",
    tags: ["Fitness", "Health"],
    category: "courses",
  },
  {
    id: 5,
    name: "Lydia Kimani",
    title: "Freelance Writer",
    rating: 4.8,
    image: "/assets/service-provider-card-placeholder.png",
    description: "I help brands tell compelling stories.",
    tags: ["Content Writing", "Storytelling"],
    category: "writing",
  },
  {
    id: 6,
    name: "Samuel Kariuki",
    title: "Product Design Mentor",
    rating: 4.6,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping juniors level up in product design.",
    tags: ["Design", "Mentorship"],
    category: "design",
  },
  {
    id: 7,
    name: "Jane Wambui",
    title: "Self-Growth Coach",
    rating: 4.7,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Empowering individuals through tailored coaching.",
    tags: ["Coaching", "Self Improvement"],
    category: "coaching",
  },
  {
    id: 8,
    name: "Michael Omondi",
    title: "Workshop Facilitator",
    rating: 4.4,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Organizing interactive learning workshops.",
    tags: ["Workshops", "Training"],
    category: "event",
  },
  {
    id: 9,
    name: "Clara Achieng",
    title: "UX Writing Expert",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Writing user-friendly and inclusive content.",
    tags: ["UX", "Writing"],
    category: "writing",
  },
  {
    id: 10,
    name: "James Mwangi",
    title: "Business Coach",
    rating: 4.6,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping startups grow sustainably.",
    tags: ["Coaching", "Business"],
    category: "consultation",
  },
  {
    id: 11,
    name: "Nadia Hussein",
    title: "Brand Strategist",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Creating impactful brand identities.",
    tags: ["Branding", "Design"],
    category: "design",
  },
  {
    id: 12,
    name: "Peter Kiprono",
    title: "Course Creator",
    rating: 4.4,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Building learning paths for digital skills.",
    tags: ["Courses", "Digital Skills"],
    category: "courses",
  },
  {
    id: 13,
    name: "Brian Muli",
    title: "Motivational Speaker",
    rating: 4.7,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Inspiring people to unlock their full potential.",
    tags: ["Speaking", "Events"],
    category: "conference",
  },
  {
    id: 14,
    name: "Salma Noor",
    title: "Content Marketing Specialist",
    rating: 4.6,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping brands grow with engaging content strategies.",
    tags: ["Marketing", "Content"],
    category: "consultation",
  },
  {
    id: 15,
    name: "Elijah Owino",
    title: "Event Organizer",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Planning and executing memorable events.",
    tags: ["Event Planning", "Workshops"],
    category: "event",
  },
  {
    id: 16,
    name: "Aisha Ahmed",
    title: "Therapist & Coach",
    rating: 4.9,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients heal and grow with therapy and coaching.",
    tags: ["Therapy", "Coaching"],
    category: "coaching",
  },
  {
    id: 17,
    name: "Mark Otieno",
    title: "Web Developer",
    rating: 4.6,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Creating responsive and accessible websites.",
    tags: ["Web Development", "Design"],
    category: "products",
  },
  {
    id: 18,
    name: "Diana Wanjiru",
    title: "Self-Publishing Consultant",
    rating: 4.7,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping authors publish their work independently.",
    tags: ["Publishing", "Writing"],
    category: "writing",
  },
  {
    id: 19,
    name: "Omar Farah",
    title: "Leadership Coach",
    rating: 4.6,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Coaching leaders to perform at their best.",
    tags: ["Leadership", "Coaching"],
    category: "masterclass",
  },
  {
    id: 20,
    name: "Helen Mutiso",
    title: "Online Educator",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Teaching courses in personal development and wellness.",
    tags: ["Courses", "Wellness"],
    category: "courses",
  },
  {
    id: 21,
    name: "John Mwangi",
    title: "Startup Consultant",
    rating: 4.8,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Advising early-stage startups on strategy and funding.",
    tags: ["Consultation", "Startups"],
    category: "consultation",
  },
  {
    id: 22,
    name: "Beatrice Wambua",
    title: "Visual Designer",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Crafting visual identities for digital products.",
    tags: ["Design", "Branding"],
    category: "design",
  },
  {
    id: 23,
    name: "Kevin Mugo",
    title: "Digital Product Coach",
    rating: 4.7,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping teams launch better digital products.",
    tags: ["Coaching", "Product"],
    category: "coaching",
  },
  {
    id: 24,
    name: "Zahra Yusuf",
    title: "Workshop Host",
    rating: 4.6,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Facilitating hands-on learning sessions.",
    tags: ["Workshop", "Community"],
    category: "event",
  },
  {
    id: 25,
    name: "Abdi Hassan",
    title: "Conference Speaker",
    rating: 4.8,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Speaking at tech and innovation conferences.",
    tags: ["Tech", "Speaking"],
    category: "conference",
  },
  {
    id: 26,
    name: "Provider 26",
    title: "Service Title 26",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 26.",
    tags: ["Tag26", "Skill"],
    category: "coaching",
  },
  {
    id: 27,
    name: "Provider 27",
    title: "Service Title 27",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 27.",
    tags: ["Tag27", "Skill"],
    category: "consultation",
  },
  {
    id: 28,
    name: "Provider 28",
    title: "Service Title 28",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 28.",
    tags: ["Tag28", "Skill"],
    category: "coaching",
  },
  {
    id: 29,
    name: "Provider 29",
    title: "Service Title 29",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 29.",
    tags: ["Tag29", "Skill"],
    category: "consultation",
  },
  {
    id: 30,
    name: "Provider 30",
    title: "Service Title 30",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 30.",
    tags: ["Tag30", "Skill"],
    category: "coaching",
  },
  {
    id: 31,
    name: "Provider 31",
    title: "Service Title 31",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 31.",
    tags: ["Tag31", "Skill"],
    category: "consultation",
  },
  {
    id: 32,
    name: "Provider 32",
    title: "Service Title 32",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 32.",
    tags: ["Tag32", "Skill"],
    category: "coaching",
  },
  {
    id: 33,
    name: "Provider 33",
    title: "Service Title 33",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 33.",
    tags: ["Tag33", "Skill"],
    category: "consultation",
  },
  {
    id: 34,
    name: "Provider 34",
    title: "Service Title 34",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 34.",
    tags: ["Tag34", "Skill"],
    category: "coaching",
  },
  {
    id: 35,
    name: "Provider 35",
    title: "Service Title 35",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 35.",
    tags: ["Tag35", "Skill"],
    category: "consultation",
  },
  {
    id: 36,
    name: "Provider 36",
    title: "Service Title 36",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 36.",
    tags: ["Tag36", "Skill"],
    category: "coaching",
  },
  {
    id: 37,
    name: "Provider 37",
    title: "Service Title 37",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 37.",
    tags: ["Tag37", "Skill"],
    category: "consultation",
  },
  {
    id: 38,
    name: "Provider 38",
    title: "Service Title 38",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 38.",
    tags: ["Tag38", "Skill"],
    category: "coaching",
  },
  {
    id: 39,
    name: "Provider 39",
    title: "Service Title 39",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 39.",
    tags: ["Tag39", "Skill"],
    category: "consultation",
  },
  {
    id: 40,
    name: "Provider 40",
    title: "Service Title 40",
    rating: 4.5,
    image: "/assets/service-provider-card-placeholder.png",
    description: "Helping clients with specific skills and services - 40.",
    tags: ["Tag40", "Skill"],
    category: "coaching",
  },
];

export const categories: Category[] = [
  { id: "all", name: "All", icon: "/assets/icons/all.svg" },
  {
    id: "consultation",
    name: "Consultation",
    icon: "/assets/icons/consultation.svg",
  },
  {
    id: "event",
    name: "Event / Workshops",
    icon: "/assets/icons/consultation.svg",
  },
  {
    id: "masterclass",
    name: "Masterclass",
    icon: "/assets/icons/masterclass.svg",
  },
  {
    id: "conference",
    name: "Conference / Events",
    icon: "/assets/icons/events.svg",
  },
  { id: "products", name: "Products", icon: "/assets/icons/products.svg" },
  {
    id: "courses",
    name: "Self-Paced Courses",
    icon: "/assets/icons/courses.svg",
  },
  { id: "coaching", name: "Coaching", icon: "/assets/icons/masterclass.svg" },
  { id: "design", name: "Design", icon: "/assets/icons/events.svg" },
  { id: "writing", name: "Writing", icon: "/assets/icons/courses.svg" },
];

export const dateFilters = [
  { id: "anytime", name: "Anytime" },
  { id: "today", name: "Today" },
  { id: "this-week", name: "This Week" },
  { id: "this-month", name: "This Month" },
];
